export default {
    install: (app) => {
        app.config.globalProperties.strings = {
            add: "Agregar",
            close: "Cerrar",
            concurrent_lesson_times: "Horarios Recurrentes",
            concurrent_lesson_times_table: "Tabla de Horarios recurrentes",
            concurrent_lesson_times_table_subtitle:
                "Aqui podras agregar los horarios que se crearan por defecto",
            create_concurrent_lessons: "Crear Horario Recurrente",
            customer: "Cliente",
            customers: "Clientes",
            customers_table: "Tabla de Clientes",
            customer_table_subtitle:
                "Aqui podras agregar, editar o borrar clientes",
            dashboard: "Dashboard",
            date: "Fecha",
            delete: "Borrar",
            delete_confirmation: "Eliminar permanentemente?",
            email: "Correo electronico",
            first_name: "Nombre",
            sale_date: "Fecha de Venta",
            last_name: "Apellido",
            lesson: "Leccion",
            lesson_detail: "Detalle de horario:",
            lesson_detail_table: "Tabla de Resevaciones",
            lesson_detail_table_subtitle:
                "Aqui podras agregar o eliminar clientes de una clase",
            lesson_status: "Estatus",
            lessons: "Lecciones",
            lessons_per_week: "Clases por semana",
            lessons_plan: "Paquete de clases",
            lessons_plans: "Paquetes de clases",
            lessons_plans_table: "Tabla de Paquetes de clases",
            lessons_plans_table_subtitle:
                "Aqui podras agregar, editar o borrar paquetes de clases",
            login: "Ingresar",
            logout: "Salir",
            monday: "Lunes",
            name: "Nombre",
            options: "Opciones",
            password: "Contraseña",
            phone_number: "Telefono",
            price: "Precio",
            reservation: "Reservacion",
            friday: "Viernes",
            reservations: "Reservaciones",
            sample_class: "Clase Muestra",
            role: "Rol",
            sale: "Venta",
            sales: "Ventas",
            sales_table: "Tabla de Ventas",
            sales_table_subtitle: "Aqui podras agregar, editar o borrar ventas",
            saturday: "Sabado",
            schedule: "Horario",
            schedules: "Horarios",
            schedules_table: "Tabla de Horarios",
            schedules_table_subtitle:
                "Aqui podras agregar, editar o borrar clientes",
            search: "Buscar",
            select_date: "Selecciona una fecha",
            soon_to_expire: "Proximos a Vencer",
            sunday: "Domingo",
            thursday: "Jueves",
            time: "Hora",
            tuesday: "Martes",
            update: "Actualizar",
            user: "Usuario",
            users: "Usuarios",
            users_table: "Tabla de Usuarios",
            users_table_subtitle:
                "Aqui podras agregar, editar o borrar usuarios",
            wednesday: "Miercoles",
            view_detail: "Ver Detalle",
            confirm_payment: "Confirmar Pago",
            description: "Descripcion",
            created_by: "Creado Por",
            assigned_to: "Asignado A",
            completation_date: "Fecha de terminacion",
            complete_confirmation: "Marcar tarea como finalizada?",
            status: "status",
            task: "Tarea",
            tasks_table: "Tabla de tareas",
            tasks_table_subtitle:
                "Aqui podras agregar, editar o borrar tareas",
        };
    },
};
